# Generated by Django 4.0.4 on 2022-06-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUser', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de usuario')),
                ('username', models.CharField(max_length=30, verbose_name='Nombre de usuario')),
                ('mail', models.CharField(max_length=60, verbose_name='Correo')),
                ('password', models.CharField(max_length=60, verbose_name='Contraseña')),
            ],
        ),
    ]
