# Generated by Django 4.0.4 on 2022-06-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Experiencia3MunozGaldamesSotoVenegas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='idUser',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nombre de usuario'),
        ),
    ]
