# Generated by Django 4.0.4 on 2022-06-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Experiencia3MunozGaldamesSotoVenegas', '0002_remove_usuarios_iduser_alter_usuarios_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='mail',
            field=models.CharField(max_length=60, unique=True, verbose_name='Correo'),
        ),
    ]
